name: Vitest Tests

env:
  VERSION: v1.10.2

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
jobs:
  vitest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install FE dependencies
        run: bun install
      - name: Download WASM DB
        run: wget https://github.com/sql-js/sql.js/releases/download/$VERSION/sqljs-wasm.zip && unzip sqljs-wasm.zip -d playground/public
      - name: Run unit tests
        run: bun run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30
