name: Bun Tests

env:
  VERSION: v1.10.2

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
jobs:
  bun_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Download WASM DB
        run: wget https://github.com/sql-js/sql.js/releases/download/$VERSION/sqljs-wasm.zip && unzip sqljs-wasm.zip -d playground/public
      - name: Install dependencies for sqljs
        run: cd src/sqljs && bun install
      - name: Run unit tests for sqljs
        run: cd src/sqljs && bun test
      - name: Install dependencies for Bun
        run: cd src/bun && bun install
      - name: Run unit tests for Bun
        run: cd src/bun && bun test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bun-report
          path: bun-report/
          retention-days: 30
